trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# ---------- BUILD STAGE ----------
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

# ---------- DEPLOY STAGE ----------
- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Application deployed successfully to Azure App Service"
      displayName: Deploy Step